config/routes.rb
Rails.application.routes.draw do
  root :to => 'bears#index'
  resources :bears
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bear.rb
class Bear < ActiveRecord::Base
  validates :name, :presence => true
  validates :cost, :presence => true
  validates :country, :presence => true
  validates :color, :presence => true
  validates :hobby, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bears_controller.rb
class BearsController < ApplicationController
  def index
    @bears = Bear.all
  end

  def show
    @bear = Bear.find(params[:id])
    render :show
  end

  def new
    @bear = Bear.new
  end

  def create
    @bear = Bear.new(bear_params)
    if @bear.save
      flash[:notice] = "Profile successfully added!"
      redirect_to  bear_path(@bear)
    else
      render :new
    end
  end

  def edit
    @bear = Bear.find(params[:id])
  end

  def update
    @bear= Bear.find(params[:id])
    if @bear.update(bear_params)
      redirect_to bears_path
    else
      render :edit
    end
  end

   def destroy
     @bear = Bear.find(params[:id])
     @bear.destroy
     redirect_to bears_path
   end


  private
  def bear_params
    params.require(:bear).permit(:name, :cost, :country, :color, :hobby)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bears/_form.html.erb
<div class = "container">
  <%= render 'layouts/errors', :object => @bear %>

  <%= form_for @bear do |f| %>
    <h5>Name:</h5>
    <%= f.text_field :name %>
    <h5>Average Number of Burritos Eaten Per Week:</h5>
    <%= f.text_field :cost %>
    <h5>Country of Origin</h5>
    <%= f.text_field :country %>
    <h5>Color: </h5>
    <%= f.text_field :color %>
    <h5>Favorite Hobbies</h5>
    <%= f.text_field :hobby %>
    <button class="waves-effect waves-light btn"><%= f.submit  %></button>
    <br>
    <br>
  <% end %>
</div>

app/views/bears/edit.html.erb
<div class = "container">
  <h1>Edit Bear</h1>


  <%= render 'form' %>

  <button class="waves-effect waves-light btn"><%= link_to "Return to bears", bears_path %></button>
  <br>
  <br>
</div>

app/views/bears/index.html.erb
<div class = "content">
</div>

  <div class="container">
    <h1>GummyBearMingle</h1>
    <h5>GummyBearMingle is an online dating site aimed at Gummy Bears who are looking for their new life partner! This site allows users to browse other bears' profiles, as well as create their own awesome dating profile! Administrators can view, edit, and remove Gummy Bear Profiles. Good Luck!</h5>
    <h2><u>Profiles</u></h2>
    <ul>
      <% @bears.each do |bear| %>
      <li><h3><%= link_to bear.name, bear_path(bear) %></li></h3>
      <% end %>
    </ul>
    <button class="waves-effect waves-light btn"><%= link_to "Create My Profile!", new_bear_path %></button>
    <br>
  </div>
</div>

app/views/bears/new.html.erb
<div class="container">
  <h1>New Profile</h1>

  <%= render "form" %>

  <button class="waves-effect waves-light btn"><%= link_to "Return Home", bears_path %></button>

</div>

app/views/bears/show.html.erb
<div class="container">
  <h1>Name: <%= @bear.name %></h1>
  <h4>Average number of Burritos eaten per week: <%= @bear.cost %></h4>
  <h4>Home Country: <%= @bear.country %></h4>
  <h4>Color: <%= @bear.color %></h4>
  <h4>Hobbies: <%= @bear.hobby %></h4>

  <button class="waves-effect waves-light btn"><%= link_to "Return to bears", bears_path %></button>
  <button class="waves-effect waves-light btn"><%= link_to "Edit", edit_bear_path %></button>
  <button class="waves-effect waves-light btn"><%= link_to "Delete", bear_path(@bear), :data => {:confirm => "You sure?", :method => 'delete'} %></button>
</div>

app/views/layouts/_errors.html.erb
<% if @bear.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @bear.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GummyBear</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <%= flash[:alert] %>
 <%= flash[:notice] %>

    <%= yield %>
  </body>
</html>